### ISSUE TITLE
Design Template for Search Projects page. 

### ISSUE THREAD

**Issue by ankur-1989** [ABenchM/abm-frontend#268]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem. It's a new feature which will enable the users an option to search the projects based on features or queries.

**Describe the solution you'd like**
This issue is responsible for creating the design template for search projects page.

**Comment by ankur-1989** [comment]
![image](https://user-images.githubusercontent.com/24721077/51983910-3b4d5c80-249a-11e9-8b94-e148c43c76f5.png)

**Comment by iamebuka** [comment]
@ankur-1989 I have a couple of questions on this issue.

- What is the endpoint to listen to for these filters?

- how does this fit into the current design of the search page

**Comment by vishaljcj** [comment]
@iamebuka @ankur-1989 
 When a user clicks on the search button, he should be able to view the search results from delphi and should be able to select the projects. As this task has dependency on MIlestone 4(Collection management workflow), it should be prioritized over the implementation of filters. The main requirement over here is that the new search response from delphi should be visible so that users can select projects for creating new collections/ adding projects to existing collections. So a simple hardcoded value for the DSL search query would suffice for now, as long as the user gets the correct delphi response. This was discussed with @nguyenLisa during today's meeting. So could you please look into this on first priority.

**Comment by ankur-1989** [comment]
@vishaljcj 
We are getting 500 server error 
java.io.IOException: Server returned HTTP response code: 500 for URL: https://delphi.cs.uni-paderborn.de/api/search

while sending the post request to Delphi. we are calling the method postSearchQuery in Delphi Controller and sending the following format of the query as JSON string - 
  {"query":"[if_icmpgt (opcode:163)> 10] "}

Could you please check at the backend and let me know if any help required from frontend?

**Comment by vishaljcj** [comment]
@ankur-1989 I checked into this. You get this error because the DSL query is not in the correct format. There is one extra space between the operand symbol(**>**) and the value entered(**10**). So, the search  query should be **[if_icmpgt (opcode:163)>10]**. As of now, if the query is not in the correct format then the delphi server returns 500 error.

**Comment by ankur-1989** [comment]
@vishaljcj 
Could you give me an example for multiple queries? 

 we have to send in json format including query as a key right?

**Comment by iamebuka** [comment]
@ankur-1989 I tried this from postman and it works 

**{"query":"[if_icmpgt (opcode:163)]>1&&[astore_3 (opcode:78)]<5"}**

**Comment by iamebuka** [comment]
@ankur-1989 can i close this issue as the pull request has been accepted?

**Comment by nguyenLisa** [comment]
Sure, feel free to do so. Please let the PG know about this on Slack. Then, please take on #289 as a follow-up task.

**Comment by iamebuka** [comment]
Issue has been resolved, pull request accepted.
