### ISSUE TITLE
Unable to select HEAD commit after changing it

### ISSUE THREAD

**Issue by johannesduesing** [ABenchM/abm-frontend#30]
Issue:
After changing the commit in an existing collection it can't be switched back to the HEAD, which is pretty confusing in my opinion since I am not sure which HEAD was initially referenced and I am not sure how to revert the change in commits if I can't select the HEAD again.

Expected behaviour:
I would expect an entry in the (tag) list of the commits with the label HEAD.

Steps to reproduce:

1. Create a new collection or select an existing one.
2. Change the selected commit.
3. Try changing it back to the HEAD.

**Comment by ankur-1989** [comment]
The Reason is -
When we create a new collection we set the value of commit to "Head"  for all the repositories because we don't know which should we select by default. which is not an actual commit in the repository. 

So when a user starts works on the collection, he/she can select a particular available commit and set if for that particular repository.

@nguyenLisa 
Do we need to change the process for this?

**Comment by nguyenLisa** [comment]
Let's select the latest version by default. @johannesduesing is right here: we should show the same things and be consistent.

**Comment by ankur-1989** [comment]
ok i'll select the latest commit from master branch.

**Comment by nguyenLisa** [comment]
Thanks!

**Comment by ankur-1989** [comment]
I looked into it. the reason we are taking head because query for search repositories does not give commit id, it gives null commits that's why we set HEAD. To set a specific commit value, we will have to call separate Rest request for each project that we are going to add. Let's do it this way then.

**Comment by nguyenLisa** [comment]
Sounds good.

**Comment by ankur-1989** [comment]
Implemented and pushed to develop branch. Closing this issue.
